config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :galleries

  get 'admin' => 'admin#index'

  root 'front#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	attachment :image

	validates :image, presence: true

  scope :default, -> {order('created_at desc').limit(20)}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
  def index
  	@body_class = 'admin'
  	@fotos = Gallery.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index
    @galleries = Gallery.default
  	
  end

  def descargables
    @galleries = Gallery.default
  	
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /galleries
  # GET /galleries.json
  def index
    @body_class = 'admin'
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @body_class = 'admin'
  end

  # GET /galleries/new
  def new
    @body_class = 'admin'

    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
    @body_class = 'admin'
    
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:desc, :image, :remove_image)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/admin/_nav.html.erb
<!-- Fixed nav -->
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= SITE_TITLE %></a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?(admin_path) %>"><%= link_to 'Home', admin_path %></li>
            <li class="<%= 'active' if current_page?(galleries_path) %>"><%= link_to 'Galeria', galleries_path %></li>

            
          </ul>

          <!-- right side of nav -->
          <ul class="nav navbar-nav navbar-right">
          	<li>
              <a href="<%= root_path %>" class="fix">
                <i class="fa fa-share" data-toggle="tooltip" data-placement="bottom" title="ir a sitio"></i>
              </a>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "fix" do %>
                <i class="fa fa-sign-out" data-toggle="tooltip" data-placement="bottom" title="salir"></i>
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/admin/index.html.erb
<%= render 'nav' %>
<div class="container text-center">
	<div class="inline-div">
		<h2><%= @fotos %></h2>
		<p>Descargables</p>
	</div>
</div>

app/views/front/descargables.html.erb
<%= render 'shared/nav' %>

<div class="" id="inicio">
    <div class="video">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL2DEiHS_oetIOdaHaVj6scWS5uDg02TgJ" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>

</div>



<section id="galeria" class="padding-b">


         <div class="menu">
            <a href="<%= root_path %>">
                <div class="menu-s <%= 'active' if current_page?(root_path) %>"><p>Hola Noticias</p></div>
            </a>
            <a href="<%= descargables_path %>">
                <div class="menu-s <%= 'active' if current_page?(descargables_path) %>"><p>Descargables</p></div>
            </a>
        </div><br>

        <div class="container-g" id="container-ms">


            <% @galleries.each do |g| %>
                <div class="item w1">
                        <a href="<%= attachment_url(g, :image) %>" data-lightbox="HolaArandas" data-title="<%= g.desc %>">
                            <%= image_tag(attachment_url(g, :image)) %>
                        </a>
                    <div class="info">
                        <p><%= g.desc %>
                        </p>
                        <div class="imgs-cont">
                           
                            <a href="<%= attachment_url(g, :image, format: 'jpg') %>" download data-toggle="tooltip" data-placement="top" title="¡Descargar!">
                                <%= image_tag('down.svg', class: "icon") %>
                            </a>
                        </div>
                    </div>
                </div>

            
            <% end %>
        </div>
</section>

<div class="back back-fixed1 text-center">
    <div class="container-fluid">
        <h3>"Voz del pueblo, voz del cielo."</h3>
    </div>
</div>

<section id="contacto" class="padding-b">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4">
                <h3 class="upper2"><b>contacto</b></h3>

            </div>
            <div class="col-lg-4"></div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <%= image_tag 'pan.png', class: "img-flex img-footer" %>
            </div>
            <div class="col-lg-4 col-sm-12 col-xs-8 col-md-12 contacto-mail">
                <p class="text-center">¿Tienes alguna duda, queja, comentario?, no dudes en comunicarte con nosotros.
                </p>
                <a href="mailto:<%= EMAIL %>">
                    <div class="button y"><%= EMAIL %></div>
                </a>
                
            </div>
            <div class="col-lg-2 col-sm-12 col-xs-12">
                <div class="row-m">
                    <a href="https://twitter.com/<%= TWITTER_USERNAME1 %>" data-toggle="tooltip" data-placement="top" title="<%= TWITTER_USERNAME1 %>">
                        <div class="bttn blue-t">
                            <%= image_tag 'twitter.svg' %>
                        </div>
                    </a>
                    <a href="<%= FACEBOOK_URL2 %>" data-toggle="tooltip" data-placement="top" title="Hola Arandas">
                        <div class="bttn blue-f">
                            <%= image_tag 'face.svg' %>
                        </div>
                    </a>
                    <a href="<%= YOUTUBE %>" data-toggle="tooltip" data-placement="top" title="Hola Arandas">
                        <div class="bttn red-y">
                            <%= image_tag 'youtube.svg' %>
                        </div>
                    </a>
                 
                </div>
                       
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>

<footer class="footer">
    <div class="container">
        <p class="text-muted">Copyright todos los derechos reservados 2015</p>
    </div>
</footer>

app/views/front/index.html.erb
<%= render 'shared/nav' %>

<div class="" id="inicio">
    <h1>#HolaNoticias</h1>
    <div class="video">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PL2DEiHS_oetIOdaHaVj6scWS5uDg02TgJ" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>

</div>



<section id="galeria" class="padding-b">


        <div class="menu">
            <a href="<%= root_path %>">
                <div class="menu-s <%= 'active' if current_page?(root_path) %>"><p>Galería</p></div>
            </a>
            
        </div><br>


        <div class="container-g" id="container-ms">


            <% @galleries.each do |g| %>
                <div class="item w1">
                        <a href="<%= attachment_url(g, :image) %>" data-lightbox="HolaArandas" data-title="<%= g.desc %>">
                            <%= image_tag(attachment_url(g, :image)) %>
                        </a>
                    <div class="info">
                        <p><%= g.desc %>
                        </p>
                        <div class="imgs-cont">
                           
                            <a href="<%= attachment_url(g, :image, format: 'jpg') %>" download data-toggle="tooltip" data-placement="top" title="¡Descargar!">
                                <%= image_tag('down.svg', class: "icon") %>
                            </a>
                        </div>
                    </div>
                </div>

            
            <% end %>
        </div>
</section>

<div class="back back-fixed1 text-center">
    <div class="container-fluid">
        <h3>"Voz del pueblo, voz del cielo."</h3>
    </div>
</div>

<section id="contacto" class="padding-b">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4">
                <h3 class="upper2"><b>contacto</b></h3>

            </div>
            <div class="col-lg-4"></div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <%= image_tag 'pan.png', class: "img-flex img-footer" %>
            </div>
            <div class="col-lg-4 col-sm-12 col-xs-8 col-md-12 contacto-mail">
                <p class="text-center">¿Tienes alguna duda, queja, comentario?, no dudes en comunicarte con nosotros.
                </p>
                <a href="mailto:<%= EMAIL %>">
                    <div class="button y"><%= EMAIL %></div>
                </a>
                
            </div>
            <div class="col-lg-2 col-sm-12 col-xs-12">
                <div class="row-m">
                    <a href="https://twitter.com/<%= TWITTER_USERNAME1 %>" data-toggle="tooltip" data-placement="top" title="<%= TWITTER_USERNAME1 %>">
                        <div class="bttn blue-t">
                            <%= image_tag 'twitter.svg' %>
                        </div>
                    </a>
                    <a href="<%= FACEBOOK_URL2 %>" data-toggle="tooltip" data-placement="top" title="Hola Arandas">
                        <div class="bttn blue-f">
                            <%= image_tag 'face.svg' %>
                        </div>
                    </a>
                    <a href="<%= YOUTUBE %>" data-toggle="tooltip" data-placement="top" title="Hola Arandas">
                        <div class="bttn red-y">
                            <%= image_tag 'youtube.svg' %>
                        </div>
                    </a>
                 
                </div>
                       
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>

<footer class="footer">
    <div class="container">
        <p class="text-muted">Copyright todos los derechos reservados 2015</p>
    </div>
</footer>

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @gallery.image_id? %>
    <p>
      <%= image_tag attachment_url(@gallery, :image, :fill, 100, 100)  %><br>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    </p>
  <% end %>
  <div class="field">
    <%= f.attachment_field :image %>
  </div>

  <div class="field">
    <%= f.text_area :desc, class: "form-control", placeholder: 'descripcion' %>
  </div>
  
  <div class="actions">
    <%= f.button 'crear', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<%= render 'admin/nav' %>

<div class="container">

	<h1>Editando foto</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @gallery %>
</div>

app/views/galleries/index.html.erb
<%= render 'admin/nav' %>
<div class="container table-responsive">
  <p id="notice"><%= notice %></p>

  <h1>Listing Galleries</h1>
  <%= link_to 'Nueva foto', new_gallery_path, class: "button pull-right" %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Descripcion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% cache do  %>
        <% @galleries.each do |gallery| %>
          <tr>
            <td><%= image_tag attachment_url(gallery, :image, :fill, 50, 50) %></td>
            <td><%= gallery.desc %></td>
            <td class="edicion">
              <%= link_to gallery do %>
                <i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="ver"></i>
              <% end %>
              <%= link_to edit_gallery_path(gallery) do %>
                <i class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="editar"></i>
              <% end %>
              <%= link_to gallery, method: :delete, data: {confirm: 'Estas seguro?'} do %>
                <i class="fa fa-remove" data-toggle="tooltip" data-placement="top" title="destruir"></i>
              <% end %>
            </td>
            
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/galleries/new.html.erb
<%= render 'admin/nav' %>
<div class="container">
	<h1>Nueva foto</h1>

	<%= render 'form' %>

	<%= link_to 'Back', galleries_path %>
</div>

app/views/galleries/show.html.erb
<%= render 'admin/nav' %>

<div class="container">
	<p id="notice"><%= notice %></p>


	<p>
	  <strong>Image:</strong>
	  <%= image_tag attachment_url(@gallery, :image, :fill, 100,100) %>
	</p>

	<p>
	  <strong>Desc:</strong>
	  <%= @gallery.desc %>
	</p>

	<%= link_to 'Edit', edit_gallery_path(@gallery) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8">
  <title><%= SITE_TITLE %></title>
  <meta name="description" content="<%= META_DESCRIPTION %>">
  <meta name="keywords" content="<%= META_KEYWORDS %>">
  <link rel="shortcut icon" href="<%= asset_path 'h-fav.png' %>">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  
  <%= csrf_meta_tags %>
</head>
<body class="<%= @body_class ? @body_class : 'default' %>">


<main class="cd-content">
	<%= yield %>
</main>	

<div class="cd-overlay-nav">
		<span></span>
</div> <!-- cd-overlay-nav -->

<div class="cd-overlay-content">
		<span></span>
</div> <!-- cd-overlay-content -->

<% if current_page?(root_path) %>
  <a href="#0" class="cd-nav-trigger">Menu<span class="cd-icon"></span></a>
<% end %>




</body>
</html>

app/views/shared/_nav.html.erb
<nav>
		<ul class="cd-primary-nav">
			<li><a class="nav" href="#inicio">Hola Noticias</a></li>
			<li><a class="nav" href="#galeria">Galería</a></li>
			<li><a class="nav" href="#contacto">Contacto</a></li>
		</ul>
</nav>